version: "3.8"

services:

  ehrbase:
    image: "ehrbase/ehrbase:0.28.0"
    environment:
      SPRING_PROFILE_ACTIVE: docker
      # SPRING_CACHE_TYPE: "caffeine" # "CAFFEINE" does not prevent redis lookups in healthcheck \_Oo_/
      SPRING_CACHE_TYPE: redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      DB_URL: ${DB_URL:-jdbc:postgresql://postgres:5432}/${DB_NAME}
      DB_USER: ${DB_USER_NAME}
      DB_PASS: ${DB_USER_PASS}
      DB_USER_ADMIN: ${DB_ADMIN_NAME}
      DB_PASS_ADMIN: ${DB_ADMIN_PASS}
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      # Actuator configs
      MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
      MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      # JAVAMELODY_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - internal
      - external
    restart: unless-stopped

  # Postgres with pre-populated ehrbase DB.
  postgres:
    image: "library/postgres:15.3-bookworm" # bookworm alpine based
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      EHRBASE_USER: ${DB_USER_NAME}
      EHRBASE_PASSWORD: ${DB_USER_PASS}
      EHRBASE_USER_ADMIN: ${DB_ADMIN_NAME}
      EHRBASE_PASSWORD_ADMIN: ${DB_ADMIN_PASS}
      PGDATA": /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - ./db/openehr-createdb.sql:/docker-entrypoint-initdb.d/openehr-createdb.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  # Redis for caching
  redis:
    image: "library/redis:7.0.12-bookworm" # bookworm alpine based
    expose:
      - "6379"
    networks:
      - internal
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  external:
    driver: bridge
  internal: {}
